// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu7Zt3uq46y7aatMq4Pk1lS7BJrWm93mc',
    appId: '1:333674237947:web:a8f6ad580847bdcd72055e',
    messagingSenderId: '333674237947',
    projectId: 'baby-shop-842f0',
    authDomain: 'baby-shop-842f0.firebaseapp.com',
    storageBucket: 'baby-shop-842f0.firebasestorage.app',
    measurementId: 'G-9Z0S2075S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6MfSHN_-XPqvpamWERxN12BfaJXAf5z8',
    appId: '1:333674237947:android:6506a4db1c4a835172055e',
    messagingSenderId: '333674237947',
    projectId: 'baby-shop-842f0',
    storageBucket: 'baby-shop-842f0.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu7Zt3uq46y7aatMq4Pk1lS7BJrWm93mc',
    appId: '1:333674237947:web:dec1373f1eea3c0572055e',
    messagingSenderId: '333674237947',
    projectId: 'baby-shop-842f0',
    authDomain: 'baby-shop-842f0.firebaseapp.com',
    storageBucket: 'baby-shop-842f0.firebasestorage.app',
    measurementId: 'G-SMZ5SDKGN1',
  );

}